#!/bin/bash


fstype=$(df -Th / | sed -n 2p |  cut -d" " -f 7)

timeshift_question () {
    echo "timeshift here"
}


btrfs_snapper() {
    ansible-playbook $(pwd)/playbooks/btrfs-snapper.yml
}

btrfs_timeshit() {

}


btrfs_question() {
    yad --image dialog-question  --title "Xerolinux btrfs question" \
        --button=Snapper:0 \
        --button=Timeshift:1 \
        --button=Cancel:2 \
        --text "What snapshot utility do you want use?"

    case $? in
        0) btrfs_snapper ;;
        1) btrfs_timeshift ;;
    esac
}


case "$fstype" in
    #case btrfs
    "btrfs") btrfs_question ;;
    # no btrfs? ok
    *) timeshift_question ;;
esac

exit 0

