#!/bin/bash


fstype=$(df -Th / | sed -n 2p |  cut -d" " -f 7)



timeshift_ext4() {
    ansible-playbook $(pwd)/playbooks/ext4-timeshift.yml
} 



btrfs_snapper() {
    ansible-playbook $(pwd)/playbooks/btrfs-snapper.yml
}

btrfs_timeshit() {
   ansible-playbook $(pwd)/playbooks/btrfs-timeshift.yml
}

timeshift_question () {
     yad --image dialog-question  --title "Xerolinux Timeshift question" \
        --button=Ok:0 \
        --button=Cancel:1 \
        --text "Do you want use Timeshift?"

    case $? in
        0) timeshift_ext4 ;;
        1) echo "exit" ;;
    esac
   
}

btrfs_question() {
    yad --image dialog-question  --title "Xerolinux btrfs question" \
        --button=Snapper:0 \
        --button=Timeshift:1 \
        --button=Cancel:2 \
        --text "What snapshot utility do you want use?"

    case $? in
        0) btrfs_snapper ;;
        1) btrfs_timeshift ;;
    esac
}


case "$fstype" in
    #case btrfs
    "btrfs") btrfs_question ;;
    # no btrfs? ok
    *) timeshift_question ;;
esac

exit 0

