#!/bin/bash


fstype=$(df -Th / | sed -n 2p | cut -d" " -f 7)


btrfs()
{
    echo "btrfs filesystem..."
    yad --image dialog-question --title Alert --button=snapper:0 --button=Timeshift:1 --text "What snapshot utility do you want use?"
}


case $fstype in 
    "btrfs") btrfs ;;
    "ext4") echo "Filesystem is EXT4!" ;;
    *) echo "Opcao Invalida!" ;;

esac
