#!/bin/bash



INPUT=$(echo -e "one \naple \ntwo\nbanana \ntree \ncitrine \nfour \nnewfruit")


RESPONSE=$(yad --title="Xerolinux btrfs Rollback" \
--text="Select the snapshot to rollback:" \
--borders=10 \
--listen \
--no-markup \
--width=500 \
--height=500 \
--no-escape \
--center \
--window-icon=gtk-preferences \
--list \
--column="ID":`snapper -c root list| sed '1,2d' |cut -d"|" -f 1` \
--column="Date":`snapper -c root list| sed '1,2d' | cut -d"|" -f 4` \
--column="User":`snapper -c root list| sed '1,2d' | cut -d"|" -f 5` \
--column="Timeline":`snapper -c root list| sed '1,2d' | cut -d"|" -f 6` \
--button="OK"!go-jump:0 \
--button="exit":1 )

echo "  DEBUG: RESPONSE = $RESPONSE"


