---
- hosts: localhost
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes  
  become: yes
  tasks:
  - name: Get Username 
    become: false
    shell: whoami
    register: username
  - debug: var=username.stdout

  - name: Install snapper and snapper-gui-git
    kewlfft.aur.aur:
      name: 
        - timeshift
        - timeshift-snap-pac
      use: paru
      state: present
    become: no        

   
  - name: Enable grub-btrfs
    ansible.builtin.systemd:
      name: grub-btrfs.path
      state: started
      enabled: yes

