---
- hosts: localhost
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes  
  become: yes
  tasks:

  - name: Check if Timeshift Exists
    stat:
      path: /usr/bin/timeshift
    register: timeshift_present
    
#  - name: Abort if the timeshift present on system
#    fail:
#      msg: "Timeshift present in your system! Exit..."
#    when: timeshift_present
#    tags:
#      - quick_exit


  - name: Install Timeshift, grub-btrfs and timeshift-snap-pac
    kewlfft.aur.aur:
      name: 
        - grub-btrfs
        - timeshift
        - timeshift-snap-pac
      use: paru
      state: present
    become: no        

   
  - name: Enable grub-btrfs
    ansible.builtin.systemd:
      name: grub-btrfs.path
      state: started
      enabled: yes

