---
- hosts: localhost
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes  
  become: yes
  tasks:

  - name: Install Timeshift, grub-btrfs and timeshift-snap-pac
    kewlfft.aur.aur:
      name: 
        - grub-btrfs
        - timeshift
        - timeshift-snap-pac
      use: paru
      state: present
    become: no        

   
  - name: Enable grub-btrfs
    ansible.builtin.systemd:
      name: grub-btrfs.path
      state: started
      enabled: yes

