---
- hosts: localhost
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes  
  become: yes
  tasks:

  - name: Install snapper and snapper-gui-git
    kewlfft.aur.aur:
      name: 
        - timeshift
      use: paru
      state: present
    become: no        

